version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/code/data
    depends_on:
      - redis
      - worker

  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/worker.Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/code/data
    depends_on:
      - redis

  redis:
    restart: unless-stopped
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
