{
 "title": "Brut Live Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Messages",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dramatiq_messages_inprogress)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Delayed Messages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dramatiq_delayed_messages_inprogress)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Messages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(dramatiq_messages_total)" }
   ]
  },
  {
   "title": "Message Processing Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(dramatiq_messages_total[5m]))"
    }
   ]
  },
  {
   "title": "Messages In Progress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "dramatiq_messages_inprogress{actor_name=\"fetch\"}",
     "legendFormat": "{{actor_name}}"
    },
    {
     "expr": "dramatiq_messages_inprogress{actor_name=\"watch\"}",
     "legendFormat": "{{actor_name}}"
    },
    {
     "expr": "dramatiq_messages_inprogress{actor_name=\"enqueue\"}",
     "legendFormat": "{{actor_name}}"
    }
   ]
  },
  {
   "title": "Brut Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{app=\"brut\"}",
     "resolution": 1
    }
   ]
  }
 ]
}