name: Publish Package
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Use Python {{ cookiecutter.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: {{ cookiecutter.python_version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip twine setuptools wheel poetry
      - name: Create Build Environment
        run: |
          poetry install
      - name: Build Package
        run: |
          poetry run invoke -e clean
          poetry run invoke -e docs.build-news -y
          poetry run invoke -e build
      - name: Publish Package
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry run python -m twine upload dist/*
